spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2testdb
#    url: jdbc:h2:mem:h2testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - file:src/main/resources/static/
        - file:src/main/resources/
        - file:src/main/public/
      add-mappings: true

  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false

#  mvc:
#    static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  issuer: buea@gmail.com
#  secret_key: Whatthefuckdoesitmeanthatyoucantgetajob
  secret_key: testSecretKey20230327testSecretKey20230327testSecretKey20230327
