spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2testdb
#    url: jdbc:h2:mem:h2testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true