### 글 쓰기
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "제목 테스트",
  "content": "잘 되는지 테스트를 해보자고"
}

### 글 삭제
DELETE http://localhost:8080/api/articles/1
Content-Type: application/json

{

}


